### ISSUE TITLE
Showing tab number only for active tab

### ISSUE THREAD

**Issue by tbusser** [MRodalgaard/atom-tab-numbers#2]
I've just installed the package but I am seeing the exact opposite behaviour from the package description. The package only shows the tab number for the tab with focus instead of showing the tab number for all tabs without focus. Since a picture says more than a thousand words:
![2016-4-6 81141 screenshots](https://cloud.githubusercontent.com/assets/5519027/14307488/a24bcbca-fbcf-11e5-9953-6d549e879dbe.png)

My setup is:
OSX v10.11.4
Atom v1.6.2
Tab-numbers v0.3.0

**Comment by mrodalgaard** [comment]
Strange, works perfect for me on the Atom Dark and One Dark themes. What theme are you using? Do you have any other packages installed that might interfere with the tabs styling?

**Comment by tbusser** [comment]
I am using the Atom Dark theme. These are the packages I've installed:
- atom-alignment@0.12.1
- atom-beautify@0.29.2
- color-picker@2.1.1
- docblockr@0.7.3
- editorconfig@1.2.4
- emmet@2.4.3
- file-icons@1.7.1
- file-types@0.5.1
- gist@0.3.1
- git-control@0.7.1
- imdone-atom@1.3.29
- js-refactor@0.6.0
- linter@1.11.4
- linter-eslint@7.1.3
- linter-jscs@3.5.0
- linter-jshint@2.1.0
- minimap@4.21.0
- open-recent@5.0.0
- project-manager@2.9.7
- refactor@0.6.0
- sort-lines@0.14.0
- tab-numbers@0.3.0
- tabs-to-spaces@1.0.2
- task-list@0.7.0
- terminal-plus@0.14.5
- todo-show
- visual-bell@1.0.0
- zentabs@0.8.7

Zentabs is a package I suspected might be interfering but after disabling it I still saw the same behaviour.

**Comment by mrodalgaard** [comment]
I also use zentabs without any problems. Would you mind inspecting the tab close button element and see what overrides https://github.com/mrodalgaard/atom-tab-numbers/blob/master/styles/tab-numbers.less#L25 .

**Comment by tbusser** [comment]
Odd, just reenabled the package and now it works fine. Not sure what has happened. Thank you for your support!
