### ISSUE TITLE
Not working for latest atom version

### ISSUE THREAD

**Issue by diminutivesloop** [MRodalgaard/atom-tab-numbers#3]
I just updated to Atom 1.9.6 and atom-tab-numbers no longer works. I’ve tried restarting atom and reinstalling the package, but the problem persists.

**Comment by lukebarton** [comment]
Did you resolve this issue? It's not working for me either.

**Comment by diminutivesloop** [comment]
It seems to be a screen resolution issue. If I connect my 13” macbook to a larger display and resize the atom window, the tab numbers eventually reappear. Although I could swear they used to display on the smaller screen.

**Comment by mrodalgaard** [comment]
Hi, you are right. I removed the tab numbers in compact mode (below 1280px width) because they didn't show correctly. I have now fixed this by making the tab label fade out before overlapping the number and pushed a new update. Thank you for the feedback.

**Comment by diminutivesloop** [comment]
Sweet! That sound like exactly the fix I was looking for.
