### ISSUE TITLE
Not working in Atom 1.18.0-beta2 (x64)

### ISSUE THREAD

**Issue by fliebe92** [MRodalgaard/atom-tab-numbers#5]
Just as the title says, it's not working in Atom 1.17.0-beta5 on Mac OS 10.12.4 (16E195).

Long story short: There are no tab numbers.

<img width="581" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8327427/26099117/0d598b3e-3a2a-11e7-8a38-caf33876f04e.png">

**Comment by mrodalgaard** [comment]
Atom 1.17.0 is released now, and it seems to work fine here. Which UI theme are you using?

**Comment by fliebe92** [comment]
Hi! I am using the following:
<img width="741" alt="bildschirmfoto 2017-05-22 um 20 28 15" src="https://cloud.githubusercontent.com/assets/8327427/26322914/3b744380-3f2d-11e7-8c82-ef2bea871ca9.png">

**Comment by mrodalgaard** [comment]
Strange. I use UI One Light as well (look below). I also tried to install [tool-bar](https://github.com/suda/tool-bar) as you have in your screenshot, but still showing tab numbers. Your UI looks different then mine (e.g. blue bar to the left of the active tab). Have you made any style custom changes?

<img width="610" alt="screen shot 2017-05-22 at 16 27 49" src="https://cloud.githubusercontent.com/assets/659763/26324247/4cdd0f62-3f32-11e7-8cef-492df193ae39.png">

**Comment by fliebe92** [comment]
Maybe my settings in the UI theme are different than yours? Could you please check this?

In addition to this, I am now using Atom 1.18 beta... maybe it's broken there.

<img width="766" alt="bildschirmfoto 2017-05-22 um 21 31 40" src="https://cloud.githubusercontent.com/assets/8327427/26325179/27d98138-3f36-11e7-9b66-ac0f800521ed.png">

**Comment by fliebe92** [comment]
I have just uninstalled your package, closed Atom and installed it again. Now it's working fine (for the moment). Thanks for your help, I will re-open this issue if I do need your help/ideas again.

Thanks! :)

**Comment by fliebe92** [comment]
Hi @mrodalgaard, it's me again.

Updated info:
- Atom 1.18.0-beta2 (x64)
- UI theme: One light
- Syntax theme: One light

I could figure out when it get's broken, so here are my steps to reproduce it:
- open Atom with no project - open a few empty tabs - everything is fine and just working.
- Add project folder - open a few empty tabs - it's broken, no tab numbers are shown.

Maybe you could spend some time to investigate the issue? That would be nice.
Please feel free to contact me to gather more information, if needed.

Thanks & cheers,
Flo

**Comment by GreatWizard** [comment]
I confirm the problem describe by @Irthen.
Same configuration, same bug.

**Comment by glutaminefree** [comment]
Same here. I'm using Atom 1.18.0 and _One Light_ UI theme

**Comment by MikiGrit** [comment]
Same here, Atom 1.19.0-beta7...

**Comment by oknixus** [comment]
Same here. I'm using Atom 1.18.0 and material UI theme

**Comment by mrodalgaard** [comment]
Sorry for the very late fix. So new version of Atom does not automatically set the pane to active if there are only one pane to show. Package is updated now :)
